### ISSUE TITLE
cros_sdk Traceback error

### ISSUE THREAD

**Issue by 3kh0** [rainestorme/auto-sh1mmer#1]
![image](https://user-images.githubusercontent.com/58097612/213722170-e4605ce8-87d2-4ec7-a62f-d904d3e41541.png)

I also can not find where the shim or anything is located

**Comment by rainestorme** [comment]
It looks like you're running on Kali. It explicitly states in the instructions to use Ubuntu 20.04 LTS. The script also shouldn't be run as root, instead as a privileged user with sudo access.

**Comment by rainestorme** [comment]
It would also be appreciated to see the entire log of the script, not just where the error occurs.

**Comment by 3kh0** [comment]
ok mb

**Comment by xHydra1337** [comment]
Ngl, had a lot of issues with this, at first I had 20.04 LTS running on a VM, with sudo access, and still didn't work, was getting the same issues as you, then I decided to dual boot my main pc with 20.04 Beta, WITH sudo access then it worked fine... honestly its really touchy and its a hit or miss.

**Comment by rainestorme** [comment]
Yeah, this script is pretty temperamental in its current state. I tested this mostly on VMs, but then again, it all depends on other external factors. I can't really change that, because it literally just runs the steps illustrated in these guides:
 - https://chromium.googlesource.com/chromiumos/platform/factory/+/HEAD/setup/RMA_SHIM.md
 - https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_guide.md
